### ISSUE TITLE
Add cyrillics version

### ISSUE THREAD

**Issue by ZAYEC77** [stones/bower-lobster#1]
Please, add cyrillics version of font

**Comment by stones** [comment]
@ZAYEC77 can you pull down https://github.com/stones/bower-lobster/tree/develop-cyrillic and check that it is what you want.

I have added it in as a separate font, so it doesn't effect others.

If it is what you want, i will merge it into master.

**Comment by ZAYEC77** [comment]
@stones yes, this is what I want, thank

**Comment by stones** [comment]
@ZAYEC77  done and done! let me know if there is anything else

**Comment by ZAYEC77** [comment]
@stones all right, thank you
